### PR TITLE
Implement an image scaling function.

### PR DESCRIPTION
**Pull request by IcaroJam**
The mlx_scale_image function first uses mlx_resize_image to create a copy of the given dimensions, then copies the raw pixel data of the original image into the new one, skipping or repeating pixels in order to make make the scaled image as faithful to the original as possible.

I've tried keeping readability and performance in mind, but some things could surely be improved.

### CODE REVIEW

**Comment by W2Wizard** [comment]
Thank you for this PR! ✨ 

I think this is worthy of a merge, my only question is if it might be better to just merge `mlx_resize_image` and `mlx_scale_image` into one because I feel like this might cause a bit of confusion.

Afterall I think for most people the common sense thought would be that resizing the image also scales the content along with it. So having two functions do roughly the same but not quite seems a bit unnecessary to me.

Additionally if you could provide some unit tests that would be great, if not I'll add them later myself.

**Comment by IcaroJam** [comment]
I myself had the problem of thinking resize would also scale the function when I first used it, so merging both seems a great idea to me!
I can take care of making both into a single function, or leave it to you if you'd prefer doing it yourself, just let me know :)

About the unit tests, I've never written proper ones, but I'll see what I can do.

**Comment by W2Wizard** [comment]
Alright, please merge them then I'll review the code :D

That's alright, I need to do them anyway. Atm there's not enough of them.

**Comment by IcaroJam** [comment]
Done!
Had to change resize's realloc to a calloc for simplicity purposes though (creating a temporal copy of the original buffer seem like too much work just to keep the realloc, specially since I don't see any benefits of using it over calloc in this case).

**Review by W2Wizard — APPROVED** [review]
Tested it myself, works great!

**Pull request merged**
